### PR TITLE
Driver and 80211n

### PR DESCRIPTION
**Pull request by krzk**
This contains minor enhancement for old wext drivers and fix for 802.11n networks.

### CODE REVIEW

**Comment by posborne** [comment]
Going back through ancient Github notifications.   This change looks good.  I no longer have the commit bit on this repo but perhaps @swstack  or @DrASK do or know who might.

**Comment by DigiEntmgmt** [comment]
Thanks, @posborne for the shout out and thanks @krzk for the PR. I am looking for someone to admin this project. I should have an answer within 24 hours.

**Comment by krzk** [comment]
Great, good to hear it!

**Comment by DigiEntmgmt** [comment]
No reply from management, so I just merged it in. Thanks for your help, @krzk

**Pull request merged**
